replicaCount: 1

image:
  repository: "registry-gitlab.pixelplex.by/768-gladwin-tech/admin"
  pullPolicy: Always
  tag: "develop"

ports:
  containerPort: 3000

imagePullSecrets: 
  - name: docker-registry-secret-admin

serviceAccount:
  create: true

service:
  type: ClusterIP

resources: 
  limits:
    cpu: 250m
    memory: 256Mi
  requests:
    cpu: 50m
    memory: 128Mi

restartPod: true

livenessProbe:
  enabled: true
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1

readinessProbe:
  enabled: true
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

ingress:
  enabled: true
  corsAllowOrigin: 
  host: 
  tls:

apiUrl: ""
landingUrl: ""
cabinetUrl: ""
nodeConfigEnv: ""
btcNetwork: ""
sentryDsn: ""
