import { accountLengthError } from '@validators/account.validators';
import { ERROR_MESSAGES } from './messages.constants';
import { MessagesErrorMap } from '../types/error.types';

export const UNKNOWN_ERROR = 'UNKNOWN_ERROR';

export enum SERVER_ERRORS {
  ACCOUNT_NAME_ALREADY_TAKEN = 'ACCOUNT_NAME_ALREADY_TAKEN',
  ACCOUNT_EMAIL_ALREADY_TAKEN = 'USER_EMAIL_ALREADY_TAKEN',
  NOT_MATCHES_TO_PATTERN = 'NOT_MATCHES_TO_PATTERN',
  INVALID_EMAIL = 'INVALID_EMAIL',
  TOO_LONG_STRING = 'TOO_LONG_STRING',
  TOO_SHORT_STRING = 'TOO_SHORT_STRING',
  EMAIL_CONFIRMATION_ERROR_INVALID_CODE = 'EMAIL_CONFIRMATION_ERROR_INVALID_CODE',
  EMAIL_CONFIRMATION_ERROR_CODE_IS_EXPIRED = 'EMAIL_CONFIRMATION_ERROR_CODE_IS_EXPIRED',
  EMAIL_ALREADY_CONFIRMED = 'EMAIL_ALREADY_CONFIRMED',
  ERROR_USER_EMAIL_IS_NOT_CONFIRMED = 'ERROR_USER_EMAIL_IS_NOT_CONFIRMED',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  ERROR_USER_SUSPENDED = 'ERROR_USER_SUSPENDED',
  AUTH_INCORRECT_PASSWORD = 'AUTH_INCORRECT_PASSWORD',
  PHONE_CONFIRMATION_ERROR_NEED_REQUEST_CODE = 'PHONE_CONFIRMATION_ERROR_NEED_REQUEST_CODE',
  PHONE_CONFIRMATION_ERROR_INVALID_CODE = 'PHONE_CONFIRMATION_ERROR_INVALID_CODE',
  PHONE_CONFIRMATION_ERROR_TOO_MANY_REQUESTS = 'PHONE_CONFIRMATION_ERROR_TOO_MANY_REQUESTS',
  ERROR_2FA_TOO_MANY_REQUESTS = 'ERROR_2FA_TOO_MANY_REQUESTS',
  EMAIL_CONFIRMATION_ERROR_TOO_MANY_REQUESTS = 'EMAIL_CONFIRMATION_ERROR_TOO_MANY_REQUESTS',
  ERROR_INVALID_EMAIL_OTP = 'ERROR_INVALID_EMAIL_OTP',
  ERROR_INVALID_OTP = 'ERROR_INVALID_OTP',
  ERROR_PHONE_ALREADY_IS_USED = 'ERROR_PHONE_ALREADY_IS_USED',
  INVALID_PHONE_NUMBER = 'INVALID_PHONE_NUMBER',
  ACCOUNT_NOT_FOUND = 'ACCOUNT_NOT_FOUND',
  PASSWORD_ALREADY_TAKEN = 'PASSWORD_ALREADY_TAKEN',
  MAINTAINER_PASSWORD_ALREADY_TAKEN = 'MAINTAINER_PASSWORD_ALREADY_TAKEN',
  USER_PASSWORD_ALREADY_TAKEN = 'USER_PASSWORD_ALREADY_TAKEN',
  ERROR_USER_STATUS_PAUSED = 'ERROR_USER_STATUS_PAUSED',
  ERROR_USER_STATUS_DELETED = 'ERROR_USER_STATUS_DELETED',
  AUTH_INVALID_ROLE = 'AUTH_INVALID_ROLE',
  ERROR_DESTINATION_NOT_PROVIDED = 'ERROR_DESTINATION_NOT_PROVIDED',
  ERROR_VERIFY_LIMIT_ATTEMPT = 'ERROR_VERIFY_LIMIT_ATTEMPT',
  ERROR_USER_INVALID_ROLE = 'ERROR_USER_INVALID_ROLE',
  EMAIL_CONFIRMATION_ERROR_INVALID_TOKEN = 'EMAIL_CONFIRMATION_ERROR_INVALID_TOKEN',
  PHONE_CONFIRMATION_ERROR_PHONE_IS_ALREADY_USED = 'PHONE_CONFIRMATION_ERROR_PHONE_IS_ALREADY_USED',
  URL_INVALID_STRATUM_URL = 'URL_INVALID_STRATUM_URL',
  URL_ALREADY_EXIST = 'URL_ALREADY_EXIST',
  ACCOUNT_GROUP_NAME_ALREADY_TAKEN = 'ACCOUNT_GROUP_NAME_ALREADY_TAKEN',
  ERROR_INVALID_THIRD_PARTY_CODE = 'ERROR_INVALID_THIRD_PARTY_CODE',
  ERROR_2FA_THIRD_PARTY_IS_NOT_PROVIDED = 'ERROR_2FA_THIRD_PARTY_IS_NOT_PROVIDED',
  ERROR_2FA_NOT_PROVIDED = 'ERROR_2FA_NOT_PROVIDED',
  AUTH_INVALID_RECAPTCHA = 'AUTH_INVALID_RECAPTCHA'
}

export const ERROR_MESSAGES_FOR_UI: MessagesErrorMap = {
  [SERVER_ERRORS.ACCOUNT_NAME_ALREADY_TAKEN]: {
    message: ERROR_MESSAGES.ACCOUNT_ALREADY_TAKEN,
  },
  [SERVER_ERRORS.ACCOUNT_EMAIL_ALREADY_TAKEN]: {
    message: ERROR_MESSAGES.EMAIL_ALREADY_TAKEN,
  },
  [SERVER_ERRORS.NOT_MATCHES_TO_PATTERN]: {
    message: ERROR_MESSAGES.ACCOUNT_INCORRECT,
  },
  [SERVER_ERRORS.INVALID_EMAIL]: {
    message: ERROR_MESSAGES.EMAIL_INCORRECT,
  },
  [SERVER_ERRORS.TOO_LONG_STRING]: {
    message: accountLengthError,
  },
  [SERVER_ERRORS.TOO_SHORT_STRING]: {
    message: accountLengthError,
  },
  [SERVER_ERRORS.EMAIL_CONFIRMATION_ERROR_INVALID_CODE]: {
    message: ERROR_MESSAGES.EMAIL_CONFIRMATION_ERROR,
  },
  [SERVER_ERRORS.EMAIL_CONFIRMATION_ERROR_CODE_IS_EXPIRED]: {
    message: ERROR_MESSAGES.EMAIL_CONFIRMATION_ERROR,
  },
  [SERVER_ERRORS.ERROR_USER_EMAIL_IS_NOT_CONFIRMED]: {
    message: ERROR_MESSAGES.ERROR_USER_EMAIL_IS_NOT_CONFIRMED,
  },
  [SERVER_ERRORS.USER_NOT_FOUND]: {
    message: ERROR_MESSAGES.USER_NOT_FOUND,
  },
  [SERVER_ERRORS.ERROR_USER_SUSPENDED]: {
    message: ERROR_MESSAGES.ERROR_USER_SUSPENDED,
  },
  [SERVER_ERRORS.AUTH_INCORRECT_PASSWORD]: {
    message: ERROR_MESSAGES.AUTH_INCORRECT_PASSWORD,
  },
  [SERVER_ERRORS.EMAIL_CONFIRMATION_ERROR_CODE_IS_EXPIRED]: {
    message: ERROR_MESSAGES.EMAIL_CONFIRMATION_ERROR_CODE_IS_EXPIRED,
  },
  [SERVER_ERRORS.EMAIL_ALREADY_CONFIRMED]: {
    message: ERROR_MESSAGES.EMAIL_ALREADY_CONFIRMED,
  },
  [SERVER_ERRORS.EMAIL_CONFIRMATION_ERROR_TOO_MANY_REQUESTS]: {
    message: ERROR_MESSAGES.TOO_MANY_REQUESTS,
  },
  [SERVER_ERRORS.PHONE_CONFIRMATION_ERROR_NEED_REQUEST_CODE]: {
    message: ERROR_MESSAGES.PHONE_CONFIRMATION_ERROR_NEED_REQUEST_CODE,
  },
  [SERVER_ERRORS.PHONE_CONFIRMATION_ERROR_INVALID_CODE]: {
    message: ERROR_MESSAGES.PHONE_CONFIRMATION_ERROR_NEED_REQUEST_CODE,
  },
  [SERVER_ERRORS.PHONE_CONFIRMATION_ERROR_TOO_MANY_REQUESTS]: {
    message: ERROR_MESSAGES.TOO_MANY_REQUESTS,
  },
  [SERVER_ERRORS.INVALID_EMAIL]: {
    message: ERROR_MESSAGES.INVALID_EMAIL,
  },
  [SERVER_ERRORS.PHONE_CONFIRMATION_ERROR_NEED_REQUEST_CODE]: {
    message: ERROR_MESSAGES.PHONE_CONFIRMATION_ERROR_NEED_REQUEST_CODE,
  },
  [SERVER_ERRORS.PHONE_CONFIRMATION_ERROR_INVALID_CODE]: {
    message: ERROR_MESSAGES.PHONE_CONFIRMATION_ERROR_NEED_REQUEST_CODE,
  },
  [SERVER_ERRORS.ERROR_2FA_TOO_MANY_REQUESTS]: {
    message: ERROR_MESSAGES.TOO_MANY_REQUESTS,
  },
  [SERVER_ERRORS.ERROR_INVALID_EMAIL_OTP]: {
    message: ERROR_MESSAGES.ERROR_INVALID_EMAIL_OTP,
  },
  [SERVER_ERRORS.ERROR_INVALID_OTP]: {
    message: ERROR_MESSAGES.ERROR_INVALID_EMAIL_OTP,
  },
  [SERVER_ERRORS.ERROR_PHONE_ALREADY_IS_USED]: {
    message: ERROR_MESSAGES.ERROR_PHONE_ALREADY_IS_USED,
  },
  [SERVER_ERRORS.INVALID_PHONE_NUMBER]: {
    message: ERROR_MESSAGES.INVALID_PHONE_NUMBER,
  },
  [SERVER_ERRORS.ACCOUNT_NOT_FOUND]: {
    message: ERROR_MESSAGES.ACCOUNT_NOT_FOUND,
  },
  [SERVER_ERRORS.PASSWORD_ALREADY_TAKEN]: {
    message: ERROR_MESSAGES.PASSWORD_ALREADY_TAKEN,
  },
  [SERVER_ERRORS.MAINTAINER_PASSWORD_ALREADY_TAKEN]: {
    message: ERROR_MESSAGES.MAINTAINER_PASSWORD_ALREADY_TAKEN,
  },
  [SERVER_ERRORS.USER_PASSWORD_ALREADY_TAKEN]: {
    message: ERROR_MESSAGES.USER_PASSWORD_ALREADY_TAKEN,
  },
  [SERVER_ERRORS.ERROR_USER_STATUS_PAUSED]: {
    message: ERROR_MESSAGES.ERROR_USER_SUSPENDED,
  },
  [SERVER_ERRORS.ERROR_USER_STATUS_DELETED]: {
    message: ERROR_MESSAGES.ERROR_USER_SUSPENDED,
  },
  [SERVER_ERRORS.AUTH_INVALID_ROLE]: {
    message: ERROR_MESSAGES.ERROR_USER_SUSPENDED,
  },
  [SERVER_ERRORS.ERROR_DESTINATION_NOT_PROVIDED]: {
    message: ERROR_MESSAGES.ERROR_USER_SUSPENDED,
  },
  [SERVER_ERRORS.ERROR_VERIFY_LIMIT_ATTEMPT]: {
    message: ERROR_MESSAGES.PHONE_CONFIRMATION_ERROR_NEED_REQUEST_CODE,
  },
  [SERVER_ERRORS.ERROR_USER_INVALID_ROLE]: {
    message: ERROR_MESSAGES.AUTH_INCORRECT_PASSWORD,
  },
  [SERVER_ERRORS.EMAIL_CONFIRMATION_ERROR_INVALID_TOKEN]: {
    message: ERROR_MESSAGES.EXPIRED_CONFIRMATION_TOKEN,
  },
  [SERVER_ERRORS.PHONE_CONFIRMATION_ERROR_PHONE_IS_ALREADY_USED]: {
    message: ERROR_MESSAGES.PHONE_CONFIRMATION_ERROR_PHONE_IS_ALREADY_USED,
  },
  [SERVER_ERRORS.URL_INVALID_STRATUM_URL]: {
    message: ERROR_MESSAGES.URL_INVALID_STRATUM_URL,
  },
  [SERVER_ERRORS.URL_ALREADY_EXIST]: {
    message: ERROR_MESSAGES.URL_ALREADY_EXIST,
  },
  [SERVER_ERRORS.ACCOUNT_GROUP_NAME_ALREADY_TAKEN]: {
    message: ERROR_MESSAGES.GROUP_NAME_ALREADY_TAKEN,
  },
  [SERVER_ERRORS.ERROR_INVALID_THIRD_PARTY_CODE]: {
    message: ERROR_MESSAGES.ERROR_INVALID_THIRD_PARTY_CODE,
  },
  [SERVER_ERRORS.ERROR_2FA_THIRD_PARTY_IS_NOT_PROVIDED]: {
    message: ERROR_MESSAGES.ERROR_2FA_THIRD_PARTY_IS_NOT_PROVIDED,
  },
  [SERVER_ERRORS.ERROR_2FA_NOT_PROVIDED]: {
    message: ERROR_MESSAGES.ERROR_2FA_NOT_PROVIDED,
  },
  [SERVER_ERRORS.ERROR_INVALID_THIRD_PARTY_CODE]: {
    message: ERROR_MESSAGES.ERROR_INVALID_THIRD_PARTY_CODE,
  },
  [SERVER_ERRORS.AUTH_INVALID_RECAPTCHA]: {
    message: ERROR_MESSAGES.AUTH_INVALID_RECAPTCHA,
  },
  [UNKNOWN_ERROR]: {
    message: ERROR_MESSAGES.UNKNOWN_ERROR,
  },
};
