{{- if .Values.ingress.enabled -}}
{{- $fullName := include "admin-frontend.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- if and .Values.ingress.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.ingress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.ingress.annotations "kubernetes.io/ingress.class" .Values.ingress.className}}
  {{- end }}
{{- end }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "admin-frontend.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/cors-allow-origin: {{ quote .Values.ingress.corsAllowOrigin }}
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
    nginx.ingress.kubernetes.io/cors-allow-methods: PUT, GET, POST, OPTIONS, DELETE, PATCH
spec:
  ingressClassName: "nginx"
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "admin-frontend.fullname" . }}
                port:
                  number: {{ .Values.ports.containerPort }}
          - path: /api/v1
            pathType: ImplementationSpecific
            backend:
              service:
                name: api-doc
                port:
                  number: 3000
          - path: /api/v1/core
            pathType: ImplementationSpecific
            backend:
              service:
                name: core-api
                port:
                  number: 3000
          - path: /api/v1/auth
            pathType: ImplementationSpecific
            backend:
              service:
                name: auth
                port:
                  number: 3000
          - path: /api/v1/admin
            pathType: ImplementationSpecific
            backend:
              service:
                name: admin-api
                port:
                  number: 3000     
{{- end }}
